kind: pipeline
type: docker
name: greeting

volumes:
- name: maven_cache
  host:
    path: /home/hao_wang_librai_tech/.drone_build/repository
- name: maven_build
  host:
    path: /home/hao_wang_librai_tech/.drone_build/maven_build

steps:
- name: en
  image: alpine
  commands:
  - echo hello world
  - mkdir -p /drone/src/repository

- name: fr
  image: maven:3.8-openjdk-17
  volumes:
  - name: maven_cache
    path: /root/.m2/repository
  commands:
  - echo bonjour monde
  - cp test.txt /tmp/test2.txt

- name: build-image
  image: plugins/docker
  dockerfile: ./Dockerfile
  registry: harbor.librai.tech
  repo: aip/try-demo



