kind: pipeline
type: docker
name: greeting

steps:
- name: en
  image: alpine
  commands:
  - echo hello world

- name: fr
  image: maven:3.8-openjdk-17
  volumes:
  - name: maven_cache
    path: /tmp
  commands:
  - echo bonjour monde
  - ls -lart /drone/src
  - ls -lart /tmp
  - cp test.txt /tmp/test2.txt


volumns:
- name: maven_cache
  host:
    path: /home/hao_wang_librai_tech/.drone_build/repository
- name: maven_build
  host:
    path: /home/hao_wang_librai_tech/.drone_build/maven_build