kind: pipeline
type: docker
name: greeting

steps:
- name: en
  image: alpine
  commands:
  - echo hello world

- name: fr
  image: maven:3.8-openjdk-17
  volumes:
  - name: build
    path: /app/build
  commands:
  - echo bonjour monde
  - cp test.txt /app/build/test2.txt

volumes:
- name: cache
  host:
    path: /home/hao_wang_librai_tech/tools/.m2