kind: pipeline
type: docker
name: greeting

steps:
- name: en
  image: alpine
  commands:
  - echo hello world

- name: fr
  image: maven:3.8-openjdk-17
  volumes:
  - name: cache
    path: /tmp/cache
  commands:
  - echo bonjour monde