kind: pipeline
type: docker
name: greeting

volumns:
- name: maven_cache
  host:
    path: /home/hao_wang_librai_tech/.drone_build/repository
- name: maven_build
  host:
    path: /home/hao_wang_librai_tech/.drone_build/maven_build

steps:
- name: en
  image: alpine
  commands:
  - echo hello world
  - mkdir -p /drone/src/repository

- name: fr
  image: maven:3.8-openjdk-17
  volumes:
  - name: maven_cache
    path: /tmp/cache
  commands:
  - echo bonjour monde
  - cp test.txt /tmp/cache/test2.txt


