kind: pipeline
type: docker
name: greeting

steps:
- name: en
  image: alpine
  commands:
  - echo hello world

- name: fr
  image: maven:3.8-openjdk-17
  volumes:
  - name: build
    path: /app_build
  commands:
  - echo bonjour monde
  - cp test.txt /drone/src
  - ls -lart /drone/src
  - cp test.txt /drone/src/test2.txt


volumns:
- name: build
  temp: {}
